name: kcbox3
description: A smart inventory management app for household storage.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  provider: ^6.1.1

  # 로컬 데이터베이스
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # 이미지 선택 (웹 제외)
  image_picker: ^1.0.4

  # 이미지 인코딩/디코딩 (Base64)
  flutter_image_compress: ^2.1.0
  image: ^4.0.17

  # 웹/앱 호환 (이미지 처리 대응)
  universal_io: ^2.2.0

  # UI
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Hive 코드 생성기
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
